### ISSUE TITLE
Implement Git Actions and Runners to initiate the model registry test-suite on pull requests.

### ISSUE THREAD

**Issue by tonyxrmdavidson** [opendatahub-io/model-registry-bf4-kf#187]
_**Tracker Task for the Implementation of GitActions/Runners for Model Registry Testing**_

When a pull request is initiated we want to run any existing golang and robot framework tests contained within the repository.
The GoLang and Robot Framework tests should be run in parallel via separate GitActions/Runners.

Git actions will be used to initiate the testing. Git runners will be used to run the testing.

The pull request cannot be merged until all tests pass.

- [x] Task 1.  [Run tests locally on laptop using the docker image](https://github.com/opendatahub-io/model-registry/issues/190)
- [x] Task 2. [Take Github Action tutorial. (Radim & Tony)](https://github.com/opendatahub-io/model-registry/issues/191)
- [x] Task 3. [Create quay.io image (public)](https://github.com/opendatahub-io/model-registry/issues/192)
- [x] Task 4 [Create gitAction to pull a quay.io image](https://github.com/opendatahub-io/model-registry/issues/193)
- [x] Task 5 [Create gitRunner to be called by the GitAction](https://github.com/opendatahub-io/model-registry/issues/194)
- [x] Task 6 [Implement simple test via GitAction / GitRunner](https://github.com/opendatahub-io/model-registry/issues/195)
- [x] Task 7 [Include GoLang tests in Git Runner](https://github.com/opendatahub-io/model-registry/issues/196)
- [x] Task 8 [Include Robot Framework tests in Git Runner](https://github.com/opendatahub-io/model-registry/issues/198)

**_Definition of Done_**

When existing tests can successfully be run on a pull request and provide correct pass/fail and accessible feedback is available for the engineer.

**Comment by rkubis** [comment]
@tonyxrmdavidson All issues are closed now, we can close this tracker too I think.
